# Generated by Django 5.1.7 on 2025-03-13 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('push_up', models.PositiveIntegerField(default=0)),
                ('squat', models.PositiveIntegerField(default=0)),
                ('press', models.PositiveIntegerField(default=0)),
                ('pull_up', models.PositiveIntegerField(default=0)),
                ('time_holding', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
    ]