# Generated by Django 5.2.4 on 2025-07-28 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='ended',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='started',
            field=models.TimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExerciseTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercisetitles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ExerciseTitle',
                'verbose_name_plural': 'ExerciseTitles',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='sport.exercisetitle'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('started', models.TimeField(auto_now=True)),
                ('ended', models.TimeField(default=None)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='sport.exercisetitle')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='sport.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
            },
        ),
        migrations.CreateModel(
            name='SetExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('repetition', models.PositiveIntegerField(default=15)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setexercises', to='sport.set')),
            ],
            options={
                'verbose_name': 'SetExercise',
                'verbose_name_plural': 'SetExercises',
            },
        ),
    ]
