# Generated by Django 5.2.4 on 2025-07-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_alter_exercise_options_remove_exercise_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='ended',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
