# Generated by Django 5.2.4 on 2025-07-28 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_alter_set_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise',
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='sport.exercise'),
        ),
        migrations.RemoveField(
            model_name='set',
            name='training',
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='training',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='sport.training'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExerciseTitle',
        ),
    ]
