# Generated by Django 5.2.4 on 2025-07-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_remove_exercise_exercise_alter_set_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='training',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='sport.training'),
            preserve_default=False,
        ),
    ]
