# Generated by Django 5.2.4 on 2025-08-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_set_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='training',
        ),
    ]
