# Generated by Django 5.2.4 on 2025-08-11 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_remove_exercise_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='setexercise',
            name='training',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='setexercisetrainings', to='sport.training'),
            preserve_default=False,
        ),
    ]
