# Generated by Django 5.2.4 on 2025-08-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_setexercise_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='setexercise',
            name='ended',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setexercise',
            name='started',
            field=models.TimeField(auto_now=True),
        ),
    ]
