# Generated by Django 5.2.4 on 2025-08-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_setexercise_ended_setexercise_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
