# Generated by Django 5.2.4 on 2025-08-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_alter_training_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='started',
            field=models.DateField(auto_now_add=True),
        ),
    ]
