# Generated by Django 5.2.4 on 2025-08-15 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0011_charts'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='charts',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='training',
            name='ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
