# Generated by Django 5.2.4 on 2025-08-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0012_charts_end_date_charts_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setexercise',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='setexercises', to='sport.exercise'),
            preserve_default=False,
        ),
    ]
