# Generated by Django 5.2.4 on 2025-08-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0013_setexercise_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setexercise',
            name='ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setexercise',
            name='started',
            field=models.DateField(auto_now=True),
        ),
    ]
