# Generated by Django 5.2.4 on 2025-08-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0014_alter_setexercise_ended_alter_setexercise_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='started',
            field=models.DateField(auto_now=True),
        ),
    ]
